INSERT INTO categories (category_id, name)
VALUES
  (12, 'Electro-portatif'),
  (13, 'Outil de batiment électrique'),
  (14, 'Soudure'),
  (15, 'Appareil Nettoyage'),
  (16, 'Mesure et tracage'),
  (17, 'Gros outillage atelier'),
  (18, 'Etabli et rangement'),
  (19, 'Outillage  main'),
  (20, 'Jardin exterieur'),
  (21, 'Plomberie'),
  (22, 'Maconnerie'),
  (23, 'Automobile'),
  (24, 'Perceuse et perforateur'),
  (25, 'Perceuse/Visseuse'),
  (26, 'Piqueur brise beton'),
  (27, 'Ponceuse'),
  (28, 'Scie electrique'),
  (29, 'Meuleuse'),
  (30, 'Poste à souder'),
  (31, 'Nettoyeur haute Pression'),
  (32, 'Injecteur / extracteur (Nettoyeur a moquette)'),
  (33, 'Aspirateur'),
  (34, 'Niveau Laser'),
  (35, 'Laser chantier/ télémètre '),
  (36, 'Scanner mural '),
  (37, 'Compresseur'),
  (38, 'Enrouleur'),
  (39, 'Marche-Pied'),
  (40, 'Coffret dépannage'),
  (41, 'Diable/Plateau roulant'),
  (42, 'Ventouse'),
  (43, 'Etabli pliant/ Table à tapisser'),
  (44, 'Décolleuse papier peint'),
  (45, 'Agrafeuse Electrique'),
  (46, 'Rainureuse/Lamelleuse'),
  (47, 'Isolation'),
  (48, 'Nettoyage'),
  (49, 'Decoupe'),
  (50, 'Poncage'),
  (51, 'Pneumatique'),
  (52, 'Echelle'),
  (53, 'echafaudage'),
  (54, 'Menuiserie');
